version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - run: yarn lint
      - run:
          name: Build for development
          command: yarn build
      - persist_to_workspace:
          root: .
          # Must be relative path from root
          paths:
            - dist
  deploy:
    docker:
      - image: timmyers/circleci-node-aws
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          working_directory: ~/repo/dist
          name: Deploy to development
          command: |
            aws s3 sync . s3://www.brewmap.co
            aws cloudfront create-invalidation --distribution-id E2BKA2AXW5LSMP --paths "/*"

workflows:
  version: 2
  deployment:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
